# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/on220149/VGA_source_bd/Base_line_top.xdc

# Block Designs: bd/VGA_source_bd/VGA_source_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd || ORIG_REF_NAME==VGA_source_bd} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0_0/VGA_source_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_clk_wiz_0_0 || ORIG_REF_NAME==VGA_source_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_c_counter_binary_0_0/VGA_source_bd_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_c_counter_binary_0_0 || ORIG_REF_NAME==VGA_source_bd_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_rst_clk_wiz_0_107M_0/VGA_source_bd_rst_clk_wiz_0_107M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_rst_clk_wiz_0_107M_0 || ORIG_REF_NAME==VGA_source_bd_rst_clk_wiz_0_107M_0} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_v_tc_0_0/VGA_source_bd_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_v_tc_0_0 || ORIG_REF_NAME==VGA_source_bd_v_tc_0_0} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_Bit_extraction1_0_1/VGA_source_bd_Bit_extraction1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_Bit_extraction1_0_1 || ORIG_REF_NAME==VGA_source_bd_Bit_extraction1_0_1} -quiet] -quiet

# XDC: bd/VGA_source_bd/VGA_source_bd_ooc.xdc
